export default {
  FETCH_INGREDIENTS: 'FETCH_INGREDIENTS',
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  FETCH_RECIPES: 'FETCH_RECIPES',
  ADD_RECIPE: 'ADD_RECIPE',
  FETCH_MENUS: 'FETCH_MENUS',
  ADD_MENU: 'ADD_MENU',
  FETCH_USERS: 'FETCH_USERS',
  ADD_USER: 'ADD_USER',
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS"
};
